# Prebuild tasks to be executed before the workspace starts
tasks:
  - name: Check if Node.js is installed
    command: |
      if ! command -v node &> /dev/null; then
        echo "Node.js is not installed. Installing..."
        nvm install 14  # Install Node.js using a specific version or package manager
      else
        echo "Node.js is already installed."
      fi

  - name: Install project dependencies and start Angular development server
    command: |
      # Install project dependencies
      npm install

  - name: Check for build errors
    command: |
      # Run Angular Build
      npm run build 

      # Start Angular development server
      npm run start

# Ports to expose for accessing services in the workspace
ports:
  - port: 3000
    onOpen: open-preview